# This workflow is used to create the necessary
# cloud infrastructure first.
# You should only run this once to get your cloud infrastructure up
# and running. Running it multiple times may create duplicate resources.
name: Create Basic Cloud Infrastructure

on:
  workflow_dispatch:

env:
  BOTO3_DEPENDENCY: "1.34.139"
  PYTHON_VERSION: "3.12"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Create Basic Cloud Infrastructure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        working-directory: ./SSG-API-Testing-Application-v2/deploy
        run: pip install boto3==${{ env.BOTO3_DEPENDENCY }}

      - name: Build Base Cloud Infrastructure
        working-directory: ./SSG-API-Testing-Application-v2/deploy
        run: python create_base_infrastructure.py
