name: Tear Down Main Infrastructure

on:
  workflow_dispatch:

jobs:
  teardown:
    runs-on: ubuntu-latest
    name: Create Docker Image and Deploy to ECR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Destroy Main Infrastructure
        id: main-infra
        working-directory: ./SSG-API-Testing-Application-v2/deploy/main-infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve
